### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by catfoolyou** [GMH-Code/Quake2-WASM#3]
After compiling, I get this error when starting the game:
```
Yamagi Quake II v8.31pre
========================
Client build options:
 - cURL HTTP downloads
 - OpenAL audio
 - Systemwide installation
Platform: Emscripten
Architecture: wasm

WASM port by Gregory Maynard-Hoare

Byte ordering: little endian

Cmd_RemoveCommand: force_centerview not added
Cmd_RemoveCommand: +mlook not added
Cmd_RemoveCommand: -mlook not added
Cmd_RemoveCommand: +joyaltselector not added
Cmd_RemoveCommand: -joyaltselector not added
Cmd_RemoveCommand: +gyroaction not added
Cmd_RemoveCommand: -gyroaction not added
Shutting down input.
recursive shutdown

```

**Comment by GMH-Code** [comment]
Hi, thanks for the report.

The project seems to build without issue in containers and virtual environments.  I can also validate that in my private test on a local server with the default shell, the game played just fine.

I know you're not going to want to hear this, but what you are trying to do on a public server (e.g. GitHub Pages) is not something I recommend or can offer support on, as I indicated in the ReadMe!

Sorry about that!

**Comment by catfoolyou** [comment]
Where is `https://quake2.m-h.org.uk/` hosted? Not a public server??

**Comment by GMH-Code** [comment]
> Where is https://quake2.m-h.org.uk/ hosted? Not a public server??

That site is licence compliant.  To reiterate what I said:

> ...***what you are trying to do*** on a public server (e.g. GitHub Pages) is not something I recommend or can offer support on...

What I was trying to be gentle in saying is this:

1. There are warnings about things you can't do placed in the READMEs, which you've not taken notice of.  Additionally, ensuring you comply with legal agreements is not my responsibility.
2. It looks like you have embedded the PAK files on a public server, which is contrary to Id's (admittedly complex) licence agreements.  I doubt you have a written exception.
3. It seems like you are *also* hosting the full game, which is taking a further risk.

You've also tried to get me to assist you, so obviously I can't do that.

The version on my site works slightly differently:

1. I have not embedded any of the Quake or Quake 2 data files.  The JS code downloads and extracts the relevant files from the original shareware archive(s) before the C code is started.  My website uses a completely separate front-end personal to myself.  This small bit of extra work is totally separate and is not subject to the GPL.
2. You can extract the PAK file and use it on your own **private** system in compliance with the licence agreement.  If you want to query this, please read it word for word and don't write a followup asking me for legal advice.
3. If you are in any doubt as to what my site is doing, I suggest you view it and look at the files your browser downloads.  You will find it only downloads Id's original archives -- my site even advertises that fact!!
4. Linux builds of Quake / Quake 2 also accept user-submitted PAK files, and/or download and use the shareware versions.  This is because the PAK files cannot be directly embedded in the distributions.  My site offers exactly the same features.
5. The version on my site can only extract and run the shareware version unless the user owns a legal copy of the full version.

I hope this makes my position clear.

Disclaimer: None of this is legal advice.
