### ISSUE TITLE
How compile it on Windows?

### ISSUE THREAD

**Issue by GonzalezAtWork** [GMH-Code/Quake2-WASM#5]
Hello! Awesome project!

trying to compile it on windows, without a success so far...

can you increase the readme to add more info about it?

Thanks!!!

**Comment by GMH-Code** [comment]
Hi @GonzalezAtWork,

Thanks for the compliment!

Out of interest, are you trying to do the build in Windows with MinGW, WSL, or something else?  I'm also curious as to how far you got, and where you got stuck.

I can probably write instructions for the above tools, but I'd need quite a lot of persuasion to support compiling/building via CMake and/or Visual Studio solutions.

**Comment by GonzalezAtWork** [comment]
didn't got far at all... Try to install the Cygwin64 to use make, but failed, so come back here to ask you directions...

about my goal on this, is to try to run Action Mod in this.
( I am also testing this: https://fte.triptohell.info/demo )

**Comment by GMH-Code** [comment]
I'll take a look when I can!

On the subject of running Quake II mods in Quake2-WASM, that's quite hard to do, so good luck -- you've got to get the gamecode to compile natively and then dynamically link in WebAssembly, which is somewhat straightforward, but the difficulty is getting the engine to successfully start the mod *and* have a player join at runtime.  I've been able to compile and load mods before, but have only ever been successful running the default game library.  This is in contrast to other Quakes which have interpreters (Quake 1) or virtual machines (Quake 3 and, I think, 4) running code, where you don't need to make any changes.

After quite extensive attempts at porting mods I was 90% sure the problem was a compatibility issue between Emscripten and the mod template originally provided by id (the default `gamex86.dll` / `gamex86.so` source given out back in the day).  Quake2-WASM is based off Yamagi Quake II, so the default game code has been somewhat modernised.  I was able to build mods natively and in WASM, but if they ran natively, they always failed when compiled to WASM.

Having said that, as the default game runs, I can say I know it is possible to run mods, but it was impossible for me to debug it without delving into the compiler source.

**Comment by GMH-Code** [comment]
I took a look for you.

I've decided I can add Windows instructions, but only if they stay in the scope of Quake2-WASM specifically.  Outside of this, I should link to the dependent projects' instructions where they can be maintained and updated by the relevant contributors.  Like the Linux ones, I want to keep them short and to the point -- Windows should be no different, otherwise I may get issue reports before people get to the point of building Quake2-WASM.  I'm not saying that's what's happened here -- besides, I've not written any help to build Quake2-WASM on Windows yet!

A few questions, as I'm curious where you got to:

- Were you successful using `git` to clone `emsdk`?
- Were you successful installing, activating and setting the environment variables for `emsdk`?
- Can you compile GL4ES (not absolutely essential for Quake2-WASM, but changes would be needed to remove support for it)?
- If GL4ES can't build, can Emscripten compile the 'Hello World' test binary?  Can you view it in your browser?
- If you were able to run `emmake make`, where did it fail?

The reason I ask is because these are all questions related to getting other projects to work.  I can give basic project-specific directions in READMEs on what is needed and which instructions to follow, but what I can't do is add extensive instructions for other projects!

Edit: Clarity.

**Comment by GonzalezAtWork** [comment]
I totally agree... Mods and such are problem for their specific projects!

Will start cloning/configuring/test and will come back to you about it.

On a parallel concern: Is it worth it just do it by linux? or even, containers?

**Comment by GonzalezAtWork** [comment]
Just did the whole building process described by you on Windows 11's WSL (using ubuntu distro) and everything worked just fine!!! I just had to force install cmake and libgl1 (not sure if needed).

so, I think you can just add for the users install WSL:

**on powershell:**
wsl --install

**and then**
apt-get update
apt-get install cmake
apt-get install libgl1

**Comment by GonzalezAtWork** [comment]
![image](https://github.com/user-attachments/assets/cbf1f18c-c65e-47b5-9e16-73211fc8401a)
![image](https://github.com/user-attachments/assets/d9db6d6b-bcde-4986-b391-196f14c3a332)

Not sure why the sizes of the files are so different from yours

**Comment by GMH-Code** [comment]
Congratulations on the successful build!

Yeah, CMake is needed for GL4ES if I remember rightly.  As I mentioned, GL4ES isn't totally necessary for this project -- I just added it because it was easier to support WebGL 1.x that way whilst still keeping almost-native WebGL 2.x.  It can be ripped out, but it's probably better to just include it.

Regarding the filesize -- it's actually correct.  My copy's the same, I'm just using GZ compression (`--best`) on the static files and forcing the client's browser to decompress it.  Ideally I should be using Brotli, but I decided it wasn't worth the time on this occasion.  Here's my copy:

```
         compressed        uncompressed  ratio uncompressed_name
             494068            25748158  98.1% quake2.wasm
```

Note the crazy `98.1%` ratio.  If you can't use GZ or Brotli compression on your web server, try adjusting the compiler optimisation level in the Makefile to `-Oz`, `-Os` or `-O2` for a smaller filesize on the WASM binaries.  The default is `-O3`, which likely produces a lot of (very compressible) inlining.  That's why your binary looks so large.

I did do lengthy benchmarks on the optimisation levels a long time ago to find the best optimisation in WASM.  `-O3` did work out to be the best overall, but I'm not sure whether that'll be the case for your system.

Edit: Just to add, no, you don't need to install libGL -- I'm not linking to the native driver.

Second edit: Fixed GL4ES typo.

**Comment by GMH-Code** [comment]
I've decided that for now I probably won't add Windows (or macOS) specific build instructions to this or any other of my WASM projects.  Since I've helped you out personally, and I've not had any similar requests elsewhere, I will close the issue.

The additions will basically always boil down to the same instructions, plus the instructions on how to use the layer.  I'm not sure recommending installing WSL on each of my WASM projects is a good idea when people may already have a different environment set up, or they may choose to use another environment and then ask me about that.  There are several alternatives and I think adding support for them is just adding work and support for something (just) outside scope, since this request isn't specific to any of my projects -- it could be applied to many of the other projects out there.
