### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by GonzalezAtWork** [GMH-Code/Quake2-WASM#6]
Hello,

https://fte.triptohell.info/demo

On this, networking is good... any chance on having that also here?

**Comment by GMH-Code** [comment]
Hi @GonzalezAtWork,

The main issue is I think both Quake-WASM and Quake2-WASM are not popular enough to have this yet.

Quake2-WASM's networking code *does* work in the browser sandbox, but it won't connect to anything because the game will likely need a bespoke WebSocket protocol driver in order to properly escape the Emscripten/WASM environment.  Once that is done the traffic can then be proxied to any regular Yamagi Quake II server.  Emscripten is meant to have some support for doing this automatically -- that is something I have not yet fully investigated, but I might take a look when I have a moment.

The user *initialed85* did write a working WebSocket driver for Quake-WASM, and the same can likely be done for Quake2-WASM, likely by altering `src/backends/unix/network.c` so it swaps out UDP for a WebSocket interface.

I am aware of FTE and that it is vastly more popular, has a lot more support behind it, and is well established.  Despite this, every time I have looked, all the game servers have been totally empty, or people present who are just trying it out for a moment, or just a few players online overall.  Servers I tried also exhibited the pre-QuakeWorld control lag, which may just be down to configuration, but it still can put new players off to even *have* control lag by default nowadays.  FTE also used to have stability issues for me in the past when I was running it on a LAN (with the default builds, anyway).

I'll close this Issue for now, but may repoen it in the future if I see enough demand!
